#!/bin/bash

# Default values
DEFAULT_VM_NAME="New VM $(date +"%+4Y-%m-%d")"
DEFAULT_VM_MEMORY=4096  # 4096 Mo = 4Gb
DEFAULT_VM_CPU=2
DEFAULT_VM_DISK_SIZE=65536  # 65536 Mo = 64 Gib
DEFAULT_VMS_FOLDER="$HOME/VirtualBox VMs"
DEFAULT_VM_NETWORK=nat
DEFAULT_VM_BOOT=
VBOX_MANAGE="/usr/bin/vboxmanage"  # Tested version: 7.0.20r163906

list_vms () {  # usage: gen-vm list
    printf "Virtual Machines list:\n\n"
    vm_list=$($VBOX_MANAGE list vms)

    while read -r data; do
        data="${data//\"}"  # remove ""

        vm_name=$(echo $data | cut -d " " -f 1)
        vm_creation_date=$($VBOX_MANAGE getextradata $vm_name creation_date)
        vm_creation_user=$($VBOX_MANAGE getextradata $vm_name creation_user)
        vm_memory=$($VBOX_MANAGE showvminfo $vm_name | awk '/Memory size:/ {print $3}')
        vm_state=$($VBOX_MANAGE showvminfo $vm_name | grep "State:" | awk -F '[()]' '{gsub(/State:                       /, ""); print $1}')  # Bidouille mais ça marche
        
        vm_disk_size="?"
        vm_medium_info=$($VBOX_MANAGE showmediuminfo disk "$DEFAULT_VMS_FOLDER/$vm_name/$vm_name.vdi" > /dev/null 2>&1)
        if [ $? == 0 ]; then
            vm_disk_size=$($VBOX_MANAGE showmediuminfo disk "$DEFAULT_VMS_FOLDER/$vm_name/$vm_name.vdi" | awk '/Capacity:/ {print $2}')
        fi
        
        echo " - Name: $vm_name"
        echo "   Memory: $vm_memory"
        printf "   Disk size: %sMB\n" $vm_disk_size
        echo "   State: $vm_state"
        echo "   Creation Date: $vm_creation_date"
        echo "   Creation User: $vm_creation_user"

        printf "\n"

    done <<< "$vm_list"

    # VBoxManage showvminfo 765f3483-b745-45fd-b0fd-b986df54b323

    # doc: https://www.virtualbox.org/manual/ch08.html#vboxmanage-list
    # get vm metadata: https://www.virtualbox.org/manual/ch08.html#vboxmanage-getextradata
}

create_vm () {  # usage: gen-vm create --name <vm name> --mem <memory> --disk <disk space> --net <network> --boot <boot type>
    vm_name=$1
    ######################################################################
    ## Vbox Documentation: https://www.virtualbox.org/manual/ch08.html ##

    # delete VM if already exists
    $VBOX_MANAGE unregistervm --delete $vm_name > /dev/null 2>&1

    # create new VM
    $VBOX_MANAGE createvm --name=$vm_name --register --ostype=Debian_64 --basefolder="$DEFAULT_VMS_FOLDER"

    # config boot type => PXE
    # https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm

    # config  memory, CPUs, NIC to NAT and boot config
    $VBOX_MANAGE modifyvm $vm_name --memory=$DEFAULT_VM_MEMORY --cpus=$DEFAULT_VM_CPU --nic1=$DEFAULT_VM_NETWORK --boot1=net
    
    # create virtual disk
    $VBOX_MANAGE createmedium disk --filename="$DEFAULT_VMS_FOLDER/$vm_name/$vm_name.vdi" --size=$DEFAULT_VM_DISK_SIZE

    # add SATA AHCI controller to use SATA drive
    $VBOX_MANAGE storagectl $vm_name --name="Sata Controller" --add=sata --controller=IntelAhci   

    # attach disk to SATA controller
    $VBOX_MANAGE storageattach $vm_name --storagectl="Sata Controller" --medium="$DEFAULT_VMS_FOLDER/$vm_name/$vm_name.vdi" --port=0 --device 0 --type hdd
    
    # config PXE boot
    # https://www.virtualbox.org/manual/ch09.html#nat-adv-tftp

    $VBOX_MANAGE modifyvm $vm_name --nattftpfile1 pxelinux.0

    # add metadata => creation date + creation user
    current_date=$(date +"%+4Y-%m-%d")
    $VBOX_MANAGE setextradata $vm_name creation_date $current_date
    $VBOX_MANAGE setextradata $vm_name creation_user $USER

    # auto logon
    # https://www.virtualbox.org/manual/ch09.html#autologon_unix
}

start_vm () {  # usage: gen-vm start <vm name>
    vm_name=$1
    $VBOX_MANAGE startvm $vm_name
}

stop_vm () {  # usage: gen-vm stop <vm name>
    vm_name=$1
    $VBOX_MANAGE controlvm $vm_name poweroff # shutdown command not supported without Guest Additions
}

destroy_vm () {  # usage: gen-vm destroy <vm name>
    vm_name=$1
    $VBOX_MANAGE  unregistervm $vm_name --delete
}

main () {
    help=false

    if [[ $# < 2 ]]; then  # if less than 2 arguments are provided, display help message
        help=true
    fi

    command=$1

    case $command in
        list | l | -l)
            list_vms
            ;;

        create | c | -c)
            if [ $help == true ]; then
                echo "usage: gen-vm create <my_new_vm>"
            else
                create_vm $2
            fi
            ;;
        
        start)
            if [ $help == true ]; then
                echo "usage: gen-vm start <vm_name>"
            else
                start_vm $2
            fi
            ;;

        stop)
            if [ $help == true ]; then
                echo "usage: gen-vm stop <vm_name>"
            else
               stop_vm $2
            fi
            ;;

        destroy)
            if [ $help == true ]; then
                echo "usage: gen-vm destroy <vm_name>"
            else
               destroy_vm $2
            fi
            ;;

        *)
            echo "gen-vm - manage VirtualBox virtual machines"
            echo ""
            echo "usage: gen-vm [-l list]"
            echo "usage: gen-vm [-c create] <my_new_vm>"
            echo "usage: gen-vm start <vm_name>"
            echo "usage: gen-vm stop <vm_name>"
            echo "usage: gen-vm destroy <vm_name>"
            ;;
    esac
}

main $@
