#!/bin/bash

# commands : create, list, start, stop 

list_vms () {
    echo "--- list VMs ---"
}

create_vm () {
    echo "--- create VM ---"
}

start_vm () {
    echo "--- start VM ---"
}

stop_vm () {
    echo "--- stop VM ---"
}

main () {
    help=false

    if [[ $# < 2 ]]; then  # if less than 2 arguments are provided, display help message
        help=true
    fi

    command=$1

    case $command in
        list | ls | l)
            list_vms
            ;;

        create | new | c | n)
            if [ $help == true ]; then
                echo "Help message for: create"
            else
                create_vm
            fi
            ;;
        
        start | up | s)
            if [ $help == true ]; then
                echo "Help message for: start"
            else
                start_vm
            fi
            ;;

        stop | down | d)
            if [ $help == true ]; then
                echo "Help message for: stop"
            else
               stop_vm
            fi
            ;;

        *)
            echo "Unknown, *display command usage*"
            ;;
    esac
}

main $@